services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=monbdd'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=van'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
